image: gitlab.dellin.ru:5005/bia-services-iaas/ci-cd-tools:deploy


stages:
    - build_image
    - update_server

main:
    tags:
        - dind-socket
    stage: build_image
    before_script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    script:
        - cd ./docker-vsftpd
        - export IMAGE_NAME="$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
        - echo "$IMAGE_NAME"
        - docker build -t $IMAGE_NAME .
        - docker push $IMAGE_NAME
        - docker tag $IMAGE_NAME  "$CI_REGISTRY_IMAGE:latest"
        - docker push "$CI_REGISTRY_IMAGE:latest"
    #only:
      #changes:
        #- "./docker-vsftpd/**/*"
        #- "./docker-vsftpd/*"

# update_server:
#     tags:
#         - dind-socket
#     stage: update_server
#     variables:
#       ANSIBLE_TIMEOUT: 60
#     image: gitlab.dellin.ru:5005/docker/origin/willhallonline/ansible:2.9.27-buster
#     script:
#       - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
#       - eval $(ssh-agent -s)
#       - echo "$SSH_ANSIBLE" | tr -d '\r' | ssh-add -
#       - mkdir -p ~/.ssh
#       - chmod 700 ~/.ssh
#       - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
#       - mkdir -p ~/.ansible/collections/ansible_collections/ansible/posix
#       - tar xfz ./ansible/ansible-posix-1.3.0.tar.gz -C ~/.ansible/collections/ansible_collections/ansible/posix/
#       - ansible-playbook ./ansible/playbook.yml -i ./conf/server.conf
#     only:
#       variables: [$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH]
